# Generated by Django 6.0.6 on 2026-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Buenos Aires', 'Buenos Aires'), ('CABA', 'CABA'), ('Córdoba', 'Córdoba'), ('Santa Fe', 'Santa Fe')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('worker', 'Trabajador'), ('client', 'Cliente')], default='', max_length=10),
        ),
    ]
