# Generated by Django 6.0.6 on 2026-06-16 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0002_alter_usuario_calle_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('electricista', 'Electricista'), ('plomero', 'Plomero'), ('pintor', 'Pintor'), ('albanil', 'Albañil'), ('carpintero', 'Carpintero'), ('gasista', 'Gasista'), ('jardinero', 'Jardinero'), ('cerrajero', 'Cerrajero'), ('mecanico', 'Mecánico'), ('tecnico', 'Técnico electrodomésticos'), ('limpieza', 'Limpieza'), ('fletes', 'Fletes y mudanzas'), ('otro', 'Otro')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-creada_en']},
        ),
        migrations.RemoveField(
            model_name='perfilworker',
            name='categoria',
        ),
        migrations.AddField(
            model_name='perfilclient',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfilclient',
            name='cantidad_resenas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='cantidad_resenas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='zona_trabajo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('electricista', 'Electricista'), ('plomero', 'Plomero'), ('pintor', 'Pintor'), ('albanil', 'Albañil'), ('carpintero', 'Carpintero'), ('gasista', 'Gasista'), ('jardinero', 'Jardinero'), ('cerrajero', 'Cerrajero'), ('mecanico', 'Mecánico'), ('tecnico', 'Técnico electrodomésticos'), ('limpieza', 'Limpieza'), ('fletes', 'Fletes y mudanzas'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Buenos Aires', 'Buenos Aires'), ('CABA', 'CABA'), ('Córdoba', 'Córdoba'), ('Santa Fe', 'Santa Fe'), ('Mendoza', 'Mendoza'), ('Tucumán', 'Tucumán'), ('Entre Ríos', 'Entre Ríos'), ('Salta', 'Salta'), ('Misiones', 'Misiones'), ('Chaco', 'Chaco'), ('Corrientes', 'Corrientes'), ('Santiago del Estero', 'Santiago del Estero'), ('San Juan', 'San Juan'), ('Jujuy', 'Jujuy'), ('Río Negro', 'Río Negro'), ('Neuquén', 'Neuquén'), ('Formosa', 'Formosa'), ('Chubut', 'Chubut'), ('San Luis', 'San Luis'), ('Catamarca', 'Catamarca'), ('La Rioja', 'La Rioja'), ('La Pampa', 'La Pampa'), ('Santa Cruz', 'Santa Cruz'), ('Tierra del Fuego', 'Tierra del Fuego')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='workers', to='changamas_proyecto.categoriaworker'),
        ),
        migrations.CreateModel(
            name='ProyectoWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='proyectos_worker/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='changamas_proyecto.perfilworker')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_escritas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='changamas_proyecto.perfilclient')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='changamas_proyecto.publicacion')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='changamas_proyecto.perfilworker')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='changamas_proyecto.publicacion')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('publicacion', 'worker')},
            },
        ),
    ]
