# Generated by Django 6.0.6 on 2026-06-16 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0003_categoriaworker_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilworker',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='worker',
        ),
        migrations.AlterUniqueTogether(
            name='solicitudworker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solicitudworker',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='solicitudworker',
            name='worker',
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
        migrations.RenameField(
            model_name='proyectoworker',
            old_name='creado_en',
            new_name='subido_en',
        ),
        migrations.RemoveField(
            model_name='perfilclient',
            name='cantidad_resenas',
        ),
        migrations.RemoveField(
            model_name='perfilworker',
            name='cantidad_resenas',
        ),
        migrations.RemoveField(
            model_name='perfilworker',
            name='zona_trabajo',
        ),
        migrations.AddField(
            model_name='perfilclient',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('plomero', 'Plomero'), ('electricista', 'Electricista'), ('pintor', 'Pintor'), ('carpintero', 'Carpintero'), ('albanil', 'Albañil'), ('gasista', 'Gasista'), ('cerrajero', 'Cerrajero'), ('jardinero', 'Jardinero'), ('techista', 'Techista'), ('otros', 'Otros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Buenos Aires', 'Buenos Aires'), ('CABA', 'CABA'), ('Córdoba', 'Córdoba'), ('Santa Fe', 'Santa Fe'), ('Mendoza', 'Mendoza'), ('Tucumán', 'Tucumán'), ('Salta', 'Salta'), ('Chaco', 'Chaco'), ('Misiones', 'Misiones'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Santiago del Estero', 'Santiago del Estero'), ('San Juan', 'San Juan'), ('Jujuy', 'Jujuy'), ('Río Negro', 'Río Negro'), ('Neuquén', 'Neuquén'), ('Formosa', 'Formosa'), ('Chubut', 'Chubut'), ('San Luis', 'San Luis'), ('Catamarca', 'Catamarca'), ('La Rioja', 'La Rioja'), ('La Pampa', 'La Pampa'), ('Santa Cruz', 'Santa Cruz'), ('Tierra del Fuego', 'Tierra del Fuego')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='changamas_proyecto.publicacion')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaWorker',
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='categorias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
        migrations.DeleteModel(
            name='SolicitudWorker',
        ),
    ]
