# Generated by Django 6.0.6 on 2026-06-24 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0004_remove_perfilworker_categorias_remove_resena_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilworker',
            name='cantidad_trabajos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='disponibilidad',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='en_linea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='radio_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilworker',
            name='ultima_vez',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_dadas', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='changamas_proyecto.perfilworker')),
            ],
        ),
    ]
