# Generated by Django 6.0.6 on 2026-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0005_perfilworker_cantidad_trabajos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='precio_presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
    ]
