# Generated by Django 6.0.6 on 2026-06-27 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0006_solicitud_detalle_solicitud_precio_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='client_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='worker_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion', models.IntegerField()),
                ('trabajo', models.IntegerField()),
                ('hospitalidad', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='changamas_proyecto.chat')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
