# Generated by Django 6.0.6 on 2026-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changamas_proyecto', '0007_chat_client_completo_chat_worker_completo_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='fecha_hora_encuentro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
